### ISSUE TITLE
Difference between/purpose of X-Message-Id and X-Transaction-Id?

### ISSUE THREAD

**Issue by brylie** [finnishtransportagency/lippu-api#2]
Our ops consultant (@alapto) was reviewing this API design with me, and was wondering why there is both a `X-Message-Id` and `X-Transaction-Id` headers. What is the purpose of those headers? How do they differ? Are they somewhat redundant?

**Comment by brylie** [comment]
It seems like the `X-Message-Id` could be deprecated in favor of `X-Transaction-ID`, improving consistency across endpoints.

**Comment by markkuko** [comment]
The idea is to use X-Transaction-Id as a unique identifier for a whole request chain. For example if there are over two interacting parties, 
the initating party generates an unique X-Transaction-Id and others use the same X-Transaction-Id throughout the request chain.

The X-Message-Id on the other hand is always set to an unique value by the processing party.

I can improve attribute descriptions to make it clearer.
