### ISSUE TITLE
POST /auth/init responses: 405 contains wrong error message

### ISSUE THREAD

**Issue by brylie** [finnishtransportagency/lippu-api#3]
The POST */auth/init* and */auth/commit* documentation contains a duplicate error message for the **405 error case**:
![screenshot from 2017-11-16 12-41-35](https://user-images.githubusercontent.com/17307/32887187-b00c4df8-cacb-11e7-940a-405277da96c8.png)

It seems to have been copied from the 403, and not updated.

**Comment by markkuko** [comment]
Thank you noticing this. I added example responses for the error cases (previously it just used the one we had defined the ApiError-object).
