### ISSUE TITLE
/availability: replace date with arrivalTime and departureTime

### ISSUE THREAD

**Issue by nighthawk** [finnishtransportagency/lippu-api#6]
The `/availability` end currently only allows specifying the departureTime. A potential use case is also answering the question "I need to be at the airport at 3pm. What options are available to get me there on time?"

This can be achieved by replacing `date` with `departureTime` and `arrivalTime`. Both should be optional. If both are provided, maybe `arrivalTime` should be ignored. If neither is provided a departure time of the current datetime can be used as now.

(By the way, `date` is currently marked as required, but the description says it's optional.)

**Comment by markkuko** [comment]
Thank you for filing this issue.

We decided to rename the departureTime and arrivalTime to departureTimeEarliest and arrivalTimeLatest in the request, possibly in the future we could add departureTimeLatest and arrivalTimeEarliest to have time interval for departure and arrival.

Good that you noticed the optional text in the descriptions, the {date} will be required path parameter and the text will be removed.
